Add XP version bump to eap-version-bump.sh
jboss-set/auxilia pull request #17
Opened 2020-07-02 09:49 UTC by xstefank

2020-07-02 10:03 UTC, spyrkob commented
That's going to fail if/when we go into CP10+ isn't it?

2020-07-02 10:08 UTC, xstefank commented
@spyrkob yes, I don't think that is the issue since we will need to remove this with XP 2.0.0 nevertheless. And I expect that will be before 7.3.10.

2020-07-02 10:35 UTC, xstefank commented
@spyrkob better safe than sorry :) , updated with your request.

2020-07-02 10:56 UTC, spyrkob commented
nice :)

2020-07-02 12:12 UTC, rpelisse commented on eap-version-bump.sh
> +readonly XP_PRODUCT_VERSION="1.0.$(($(echo $NEXT_VERSION | sed -e "s/.*\.\(.*\)$/\1/") - 1)).GA"
@spyrkob a bit too many parenthesis in this one, it makes me nervous :)

What about moving this part into a readonly var: $(echo $NEXT_VERSION | sed -e "s/.*\.\(.*\)$/\1/") - 1)    (if nothing else, for visibility purpose)

2020-07-02 12:27 UTC, xstefank commented on eap-version-bump.sh
> +readonly XP_PRODUCT_VERSION="1.0.$(($(echo $NEXT_VERSION | sed -e "s/.*\.\(.*\)$/\1/") - 1)).GA"
surprise @rpelisse! Who made the PR!!! :D will do.

2020-09-02 10:00 UTC, spyrkob commented
@rpelisse can we merge this one?

2020-09-02 12:11 UTC, rpelisse requested changes

2020-09-02 12:11 UTC, rpelisse commented on eap-version-bump.sh
> +readonly XP_PRODUCT_VERSION="1.0.$(($XP_MINOR_VERSION - 1)).GA"
I'm not sure what the meaning of $(( )) ? What does it do (compare to $() ) ? Oh I guess it allows to do math operation, right? I would use expr for this it is more explicit:

$( expr "${XP_MINOR_VERSION}" - 1 ) 

Also I would "protect" $XP_MINOR_VERSION => ${XP_MINOR_VERSION}

2020-09-03 06:48 UTC, xstefank commented
@rpelisse updated.

2020-09-03 09:07 UTC, merged