Remove need to provide versions as arguments
jboss-set/auxilia pull request #18
Opened 2020-07-02 10:22 UTC by spyrkob

Instead of using arguments to specify old/new version read it from config files

This builds on top of #16 - temporary included it in here

2020-07-02 12:51 UTC, spyrkob commented on eap-version-bump.sh
> +  major=`echo ${version} | cut -d '.' -f 1`
Old habits die hard? ;) Fixed now

2020-09-03 09:13 UTC, rpelisse requested changes

2020-09-03 09:13 UTC, rpelisse commented on eap-version-bump.sh
> +readonly PRODUCT_VERSION_REGEXP="Red Hat JBoss Enterprise Application Platform - Version (.*)"
As it is, if there files matching .* or (.*) in the current directory the content of this var is going to change. I would recommmend single quoting to ensure the metachar * is NOT interpreted.

2020-09-03 09:13 UTC, rpelisse commented on eap-version-bump.sh
> +CURRENT_PRODUCT_VERSION=$(cat ${PRODOCT_VERSION_ALT_TXT})
I'll add double-quote around the var to protect against spaces in the file name.

2020-09-03 09:13 UTC, rpelisse commented on eap-version-bump.sh
> +echo $text
Shouldn't this be removed? If not, it should be "${text}"

2020-09-03 09:13 UTC, rpelisse commented on eap-version-bump.sh
> +if [[ ${CURRENT_PRODUCT_VERSION} =~ ${PRODUCT_VERSION_REGEXP} ]]; then
Double quote around both var to protect from misinterpretation in case whitespaces are in the value.

2020-09-03 09:13 UTC, rpelisse commented on eap-version-bump.sh
> +  micro=$(echo ${version} | cut -d '.' -f 3)
double quote around ${version} (there is a pattern here :) )

2020-09-03 09:13 UTC, rpelisse commented on eap-version-bump.sh
> +  NEXT_VERSION="${major}.${minor}.$((micro+1))"
I honestly don't know if $(( <math operation )) is better than $( expr ). :thinking:

2020-09-03 09:13 UTC, rpelisse commented on eap-version-bump.sh
> +  NEXT_XP_VERSION="1.0.${micro}.GA"
Shouldn't the for variables be readonly, shouldn't they?

2020-09-03 09:13 UTC, rpelisse commented on eap-version-bump.sh
> -readonly PRODOCT_VERSION_ALT_TXT=${PRODOCT_VERSION_ALT_TXT:-'galleon-pack/src/main/resources/packages/version.txt/content/version.txt'}
PRODOCT => PRODUCT ;)

2020-09-03 09:42 UTC, spyrkob commented on eap-version-bump.sh
> +if [[ ${CURRENT_PRODUCT_VERSION} =~ ${PRODUCT_VERSION_REGEXP} ]]; then
It looks like the regexp itself cannot be quoted

2020-09-03 09:42 UTC, spyrkob commented on eap-version-bump.sh
> +  NEXT_XP_VERSION="1.0.${micro}.GA"
they can't be readonly because they override the default command line arguments. Or am I missing something?

2020-09-03 09:52 UTC, rpelisse commented on eap-version-bump.sh
> +if [[ ${CURRENT_PRODUCT_VERSION} =~ ${PRODUCT_VERSION_REGEXP} ]]; then
Ojh right, but CURRENT_PRODUCT_VERSION should be quoted, no?

2020-09-03 09:52 UTC, rpelisse commented on eap-version-bump.sh
> +  NEXT_XP_VERSION="1.0.${micro}.GA"
Then not :)

2020-09-03 09:55 UTC, spyrkob commented on eap-version-bump.sh
> +if [[ ${CURRENT_PRODUCT_VERSION} =~ ${PRODUCT_VERSION_REGEXP} ]]; then
yup :)

2020-09-03 10:09 UTC, spyrkob commented
@rpelisse changes are in. Thanks for review 👍

2020-09-03 10:10 UTC, rpelisse commented on eap-version-bump.sh
> -readonly PRODOCT_VERSION_ALT_TXT=${PRODOCT_VERSION_ALT_TXT:-'galleon-pack/src/main/resources/packages/version.txt/content/version.txt'}
@spyrkob this still needs to be fixed ;)

2020-09-03 10:37 UTC, spyrkob commented on eap-version-bump.sh
> -readonly PRODOCT_VERSION_ALT_TXT=${PRODOCT_VERSION_ALT_TXT:-'galleon-pack/src/main/resources/packages/version.txt/content/version.txt'}
I think I corrected it everywhere in the script, it just shows in the removed lines in diff

2020-09-03 10:40 UTC, merged