Add support to hub
jboss-set/auxilia pull request #32
Opened 2024-07-08 10:39 UTC by iweiss

2024-07-09 08:10 UTC, rpelisse requested changes
A few enhancements, but looks good apart from that.

2024-07-09 08:10 UTC, rpelisse commented on pr-merge
> +    hub api $1
Small enhacement:

`$1 => "${1}"`

Unless, ${1} is expanding into several values, separated by spaces, then you need to omit the double quotes (so if the value is an URL, double quote is good, if $1 expands into, let's say an URL and then an extra argument, double quotes need to be omited).

2024-07-09 08:10 UTC, rpelisse commented on pr-merge
> +    curl -L -s -n $1
Same $1 => "${1}" (or just ${1}).

2024-07-09 08:10 UTC, rpelisse commented on pr-merge
> +readonly PULL=$(apiCommand $PR_GITHUB_API_URL)
`$PR_GITHUB_API_URL => "${PR_GITHUB_API_URL}"`

Here I think double quote are mandatory as you are clear passing an URL (so one value).

2024-07-09 08:10 UTC, rpelisse commented on pr-merge
> -readonly PULL=$(curl -L -s -n ${PR_GITHUB_API_URL})
`${PR_GITHUB_API_URL} => "${PR_GITHUB_API_URL}"`

2024-07-09 08:10 UTC, rpelisse commented on pr-merge
> +if [ "$(echo ${PULL} | jq .status)" == "\"404\"" ]; then
Double quote around the command subsitution are not needed, so I would suggest to remove them, so you can put them around the variable replacement:

`if [ $(echo "${PULL}" | jq .status) == ...`

For the second half, rather than escaping with backquote the double quotes, I would simply use simple quote:

`... == '"404"' ]; then
`

2024-07-09 08:10 UTC, rpelisse commented on pr-merge
> +  echo ${PULL}
Maybe add a stmt before the print of the var ("Resulting PULL operation: ${PULL}").

Unless, of course, the result is echoed to be used by something else. In this case, just add the double quote around ${PULL} to ensure bash threats the result as "one value".

2024-07-10 07:55 UTC, iweiss commented
Should look better now

2024-07-10 08:16 UTC, rpelisse approved these changes

2024-07-10 08:31 UTC, iweiss commented
Fair enough, changed!

2024-07-11 07:00 UTC, rpelisse approved these changes

2024-07-11 07:00 UTC, merged