Fix for curl usage
jboss-set/auxilia pull request #33
Opened 2024-12-25 06:04 UTC by roastedcpu

2024-12-27 15:48 UTC, rpelisse requested changes
Looks pretty good to me, but I found a couple of possible enhancements.

2024-12-27 15:48 UTC, rpelisse commented on pr-merge
> +if [ "$(echo "${PULL}" | jq '.status')" == "404" ]; then
better than `'"404"'`, but the best would `'404'`

2025-01-01 19:11 UTC, roastedcpu commented on pr-merge
> +  if ! isHubInstalled; then
I actually asked chatGPT for this one:

if [ ! foo ]; then

What happens here?

Bash interprets [ ] as a test command, which is used to evaluate certain conditions, like file existence, string comparisons, or numeric comparisons.
The part inside the brackets ([ ! foo ]) needs to be a valid expression that the test command can process.
Why doesn’t it work with a method?

foo is a method, meaning it needs to be executed as a command to return an exit status.
However, [ ! foo ] doesn’t execute foo. Instead, Bash treats foo as a literal string and tries to evaluate it as part of the test command.
Since foo isn’t a valid test expression (like -e for file existence or a string comparison), Bash throws an error.

2025-01-02 07:57 UTC, rpelisse commented on pr-merge
> +  if ! isHubInstalled; then
Oh, believe or not, I've never put a function call in such a test, so I never ran into this one. Good to know and good on ChatGPT to know intricacies of Bash interpretation mecanisms better than most people!

2025-01-02 07:57 UTC, rpelisse approved these changes
LGTM

2025-01-02 07:57 UTC, merged